URL = 'url'
INVALID_URL_MESSAGE = 'Invalid URL'
URL_IS_NOT_SAFE_MESSAGE = 'URL is not safe'
URL_NOT_EXIST_MESSAGE = 'URL does not exist'
URL_EXIST_MESSAGE = 'URL is already exist'
URL_REQUIRED_MESSAGE = 'URL is required'
VIRUS_TOTAL_BASE_URL = 'https://www.virustotal.com/api/v3'
