# Generated by Django 5.2.3 on 2025-07-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLInformationModel',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=15)),
                ('title', models.TextField(blank=True)),
                ('images', models.JSONField(default=list)),
                ('stylesheets', models.IntegerField()),
            ],
        ),
    ]
